name: Update WSG Data

on: 
  workflow_dispatch:

jobs:
  Update-WSG-Data:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Install bundler
            run: | 
              sudo gem install bundler
              sudo chmod -R 777 /var/lib/gems/

          - name: Install gems via bundle
            run: bundle install

          - name: List all files
            run: ls -l

          - name: List files in 'scripts'
            run: find scripts
          
          - name: Change to 'scripts' directory and run 'save.rb'
            run: |
              cd scripts
              ruby ./save.rb

          # - name: Where am I?
          #   run: pwd

          # - name: List everything in 'scripts'
          #   run: find .
          
          # - name: Run script 'save.rb'
          #   run: ruby ./save.rb
          
          - name: List all files in 'data' directory
            run: ls ./data